version: '2.1'
orbs:
  browser-tools: circleci/browser-tools@1.4.1
jobs:
  build:
    docker:
      - image: cimg/python:3.11.1
    steps:
      - checkout
      - run: 
          command: pip3 install -r requirements.txt
          name: Installing Dependencies
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - run: 
          command: pytest --spec --headless
          name: Running Pytest Tests
